# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import iris_classifier_pb2 as iris__classifier__pb2


class ClassifyIrisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.classify = channel.unary_unary(
                '/ClassifyIris/classify',
                request_serializer=iris__classifier__pb2.inputArray.SerializeToString,
                response_deserializer=iris__classifier__pb2.outputArray.FromString,
                )


class ClassifyIrisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def classify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifyIrisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'classify': grpc.unary_unary_rpc_method_handler(
                    servicer.classify,
                    request_deserializer=iris__classifier__pb2.inputArray.FromString,
                    response_serializer=iris__classifier__pb2.outputArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClassifyIris', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClassifyIris(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClassifyIris/classify',
            iris__classifier__pb2.inputArray.SerializeToString,
            iris__classifier__pb2.outputArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
